import { WorkOrder, StaffUser } from "@/types/work-order";

export const MOCK_STAFF: StaffUser[] = [
  {
    id: "sup-sarah",
    name: "Sarah Miller (Supervisor)",
    role: "SUPERVISOR",
    avatar: "SM",
    specialty: "Team Lead & Final Sign-Off",
    email: "sarah.m@workpulse.internal",
  },
  {
    id: "sup-david",
    name: "David Vance (Supervisor)",
    role: "SUPERVISOR",
    avatar: "DV",
    specialty: "Electrical & Safety Lead",
    email: "david.v@workpulse.internal",
  },
  {
    id: "wrk-alex",
    name: "Alex Chen",
    role: "WORKER",
    avatar: "AC",
    specialty: "Mechanical Repairs",
    email: "alex.c@workpulse.internal",
  },
  {
    id: "wrk-maria",
    name: "Maria Garcia",
    role: "WORKER",
    avatar: "MG",
    specialty: "Computer & Diagnostics",
    email: "maria.g@workpulse.internal",
  },
  {
    id: "wrk-james",
    name: "James Wilson",
    role: "WORKER",
    avatar: "JW",
    specialty: "Pipes & Heavy Tools",
    email: "james.w@workpulse.internal",
  },
  {
    id: "wrk-elena",
    name: "Elena Rostova",
    role: "WORKER",
    avatar: "ER",
    specialty: "Sensors & Testing",
    email: "elena.r@workpulse.internal",
  },
];

const now = new Date();
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60 * 1000).toISOString();
const hoursFromNow = (hrs: number) => new Date(now.getTime() + hrs * 60 * 60 * 1000).toISOString();

export const INITIAL_WORK_ORDERS: WorkOrder[] = [
  {
    id: "WO-101",
    title: "Fix High-Pressure Water Valve Leak",
    clientDetails: {
      name: "Apex Energy Facilities",
      contact: "Bob Martinez (bob@apexenergy.com / 555-0192)",
    },
    status: "PENDING_ACK",
    acknowledgedBy: null,
    supervisorId: "sup-sarah",
    assignedWorkerIds: [],
    materialsCheck: [
      { item: "New rubber seal ring", ready: true },
      { item: "Replacement valve head", ready: true },
      { item: "Pressure test gauge", ready: false },
      { item: "Hand wrench set", ready: true },
    ],
    estimatedCompletionDate: hoursFromNow(3),
    createdAt: minutesAgo(35), // > 30 mins ago -> Shows overdue warning
    priority: "CRITICAL",
    slaMinutes: 20,
    station: "Room 4 - Water Pumps",
    category: "Emergency Repair",
    description: "Customer noticed water dripping from the main valve. Please check pressure and install the new rubber seal.",
    version: 1,
  },
  {
    id: "WO-102",
    title: "Update Computer Controller Software",
    clientDetails: {
      name: "Solaria Power Station",
      contact: "Lisa Wong (lisa@solaria.org / 555-0144)",
    },
    status: "PENDING_ACK",
    acknowledgedBy: null,
    supervisorId: "sup-david",
    assignedWorkerIds: [],
    materialsCheck: [
      { item: "USB drive with software update v4.2", ready: true },
      { item: "Diagnostic cable", ready: true },
      { item: "Backup battery pack", ready: false },
    ],
    estimatedCompletionDate: hoursFromNow(4),
    createdAt: minutesAgo(12), // 12 mins ago -> Yellow warning soon
    priority: "HIGH",
    slaMinutes: 25,
    station: "Desk 1 - Computer Room",
    category: "Software & Settings",
    description: "The control screen was freezing yesterday. Install the latest software update and restart the screen.",
    version: 1,
  },
  {
    id: "WO-103",
    title: "Clean Main Cooling Tank and Pipes",
    clientDetails: {
      name: "BioHealth Labs",
      contact: "Mark Davis (mark@biohealth.com / 555-0188)",
    },
    status: "IN_PROGRESS",
    acknowledgedBy: {
      userId: "wrk-alex",
      name: "Alex Chen",
      timestamp: minutesAgo(40),
    },
    supervisorId: "sup-sarah",
    assignedWorkerIds: ["wrk-alex", "wrk-maria"],
    materialsCheck: [
      { item: "Cleaning soap solution (5 gallons)", ready: true },
      { item: "Fresh pipe gaskets", ready: true },
      { item: "Drain bucket & hose", ready: true },
      { item: "Protective gloves and goggles", ready: true },
    ],
    estimatedCompletionDate: hoursFromNow(2),
    createdAt: minutesAgo(50),
    priority: "MEDIUM",
    slaMinutes: 90,
    station: "Bay 2 - Cooling Room",
    category: "Regular Maintenance",
    description: "Water is flowing slower than normal. Drain the cooling tank, rinse the pipes, and replace old rubber gaskets.",
    version: 2,
  },
  {
    id: "WO-104",
    title: "Replace Robot Arm Motor",
    clientDetails: {
      name: "Quantum Parts Factory",
      contact: "Kevin Scott (kevin@quantumparts.com / 555-0177)",
    },
    status: "IN_PROGRESS",
    acknowledgedBy: {
      userId: "wrk-james",
      name: "James Wilson",
      timestamp: minutesAgo(18),
    },
    supervisorId: "sup-david",
    assignedWorkerIds: ["wrk-james"],
    materialsCheck: [
      { item: "New 400W electric motor", ready: true },
      { item: "Motor connection wire", ready: true },
      { item: "Hex tool key", ready: false },
    ],
    estimatedCompletionDate: hoursFromNow(3),
    createdAt: minutesAgo(22),
    priority: "HIGH",
    slaMinutes: 60,
    station: "Assembly Line 3",
    category: "Equipment Replacement",
    description: "The robot arm stopped moving smoothly on line 3. Replace the damaged motor with the new spare part.",
    version: 2,
  },
  {
    id: "WO-105",
    title: "Align Laser Sensor System",
    clientDetails: {
      name: "Lumina Tech Center",
      contact: "Emma Green (emma@luminatech.com / 555-0123)",
    },
    status: "QC_REVIEW",
    acknowledgedBy: {
      userId: "wrk-elena",
      name: "Elena Rostova",
      timestamp: minutesAgo(90),
    },
    supervisorId: "sup-sarah",
    assignedWorkerIds: ["wrk-elena"],
    materialsCheck: [
      { item: "Laser testing card", ready: true },
      { item: "Digital alignment level", ready: true },
      { item: "Cleanroom lens cloth", ready: true },
    ],
    estimatedCompletionDate: hoursFromNow(1),
    createdAt: minutesAgo(105),
    priority: "MEDIUM",
    slaMinutes: 120,
    station: "Room 1 - Testing Lab",
    category: "Quality Inspection",
    description: "Worker finished mounting and aligning the sensor. Ready for Supervisor Sarah to review and approve.",
    version: 3,
  },
  {
    id: "WO-106",
    title: "Monthly Backup Generator Test",
    clientDetails: {
      name: "St. Jude Hospital Data Center",
      contact: "Tom Baker (tom@stjude.org / 555-0155)",
    },
    status: "COMPLETED",
    acknowledgedBy: {
      userId: "wrk-maria",
      name: "Maria Garcia",
      timestamp: minutesAgo(200),
    },
    supervisorId: "sup-david",
    assignedWorkerIds: ["wrk-maria", "wrk-james"],
    materialsCheck: [
      { item: "Power test meter", ready: true },
      { item: "Diesel fuel check stick", ready: true },
      { item: "Battery voltage tester", ready: true },
    ],
    estimatedCompletionDate: minutesAgo(30),
    createdAt: minutesAgo(240),
    priority: "CRITICAL",
    slaMinutes: 120,
    station: "Outside - Power Yard",
    category: "Safety Check",
    description: "Turned on the backup generator and tested power transfer. Everything ran normally and passed all safety checks.",
    version: 4,
  },
];
